const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Plugins.TiledBg,
    C3.Behaviors.Pin,
    C3.Behaviors.MoveTo,
    C3.Behaviors.Tween,
    C3.Behaviors.Bullet,
    C3.Behaviors.EightDir,
    C3.Plugins.Keyboard,
    C3.Behaviors.solid,
    C3.Behaviors.scrollto,
    C3.Plugins.Spritefont2,
    C3.Behaviors.Timer,
    C3.Plugins.Particles,
    C3.Behaviors.Sin,
    C3.Plugins.Touch,
    C3.Behaviors.Rotate,
    C3.Plugins.LocalStorage,
    C3.Plugins.Audio,
    C3.Plugins.Arr,
    C3.Plugins.Mouse,
    C3.Plugins.advert,
    C3.Plugins.Json,
    C3.Plugins.AJAX,
    C3.Plugins.Text,
    C3.Plugins.Browser,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.System.Acts.SetLayerVisible,
    C3.Behaviors.Tween.Acts.TweenOneProperty,
    C3.Plugins.LocalStorage.Acts.GetItem,
    C3.Plugins.Sprite.Acts.SetVisible,
    C3.Plugins.System.Cnds.PickByEvaluate,
    C3.Plugins.System.Acts.SetVar,
    C3.Plugins.Sprite.Exps.ImagePointX,
    C3.Plugins.Sprite.Exps.ImagePointY,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.Sprite.Acts.SetInstanceVar,
    C3.Plugins.System.Cnds.PickByComparison,
    C3.Plugins.Sprite.Acts.SetPos,
    C3.Plugins.Sprite.Exps.X,
    C3.Plugins.Sprite.Exps.Y,
    C3.Behaviors.Pin.Acts.PinByProperties,
    C3.Plugins.System.Cnds.PickLastCreated,
    C3.Plugins.System.Cnds.PickAll,
    C3.Behaviors.Pin.Acts.PinByDistance,
    C3.Plugins.System.Acts.Wait,
    C3.ScriptsInEvents.Game_Event11_Act1,
    C3.ScriptsInEvents.Game_Event12_Act1,
    C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
    C3.Plugins.System.Cnds.PickRandom,
    C3.Plugins.Sprite.Acts.SetScale,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.System.Exps.random,
    C3.Plugins.Sprite.Exps.AnimationFrameCount,
    C3.Behaviors.Tween.Acts.TweenTwoProperties,
    C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
    C3.Plugins.Sprite.Exps.UID,
    C3.Plugins.System.Acts.SetBoolVar,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.Sprite.Acts.SetAngle,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.Sprite.Acts.SetOpacity,
    C3.Behaviors.solid.Acts.SetEnabled,
    C3.Plugins.Spritefont2.Acts.SetText,
    C3.Behaviors.EightDir.Acts.SetMaxSpeed,
    C3.Plugins.System.Acts.SetGroupActive,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Behaviors.Timer.Acts.StartTimer,
    C3.Plugins.System.Cnds.Else,
    C3.Behaviors.EightDir.Acts.SetVectorX,
    C3.Behaviors.EightDir.Acts.SetVectorY,
    C3.Behaviors.Timer.Acts.StopAllTimers,
    C3.Plugins.Audio.Acts.Play,
    C3.Behaviors.EightDir.Acts.SetSpeed,
    C3.Plugins.Sprite.Acts.SetCollisions,
    C3.Plugins.Sprite.Acts.SetY,
    C3.Plugins.Sprite.Exps.LayerNumber,
    C3.Plugins.Sprite.Acts.AddChild,
    C3.Plugins.Sprite.Acts.SetMeshSize,
    C3.Plugins.System.Exps.min,
    C3.Plugins.System.Cnds.Repeat,
    C3.Plugins.Sprite.Acts.SetMeshPoint,
    C3.Plugins.System.Exps.loopindex,
    C3.ScriptsInEvents.Game_Event42_Act3,
    C3.Plugins.System.Cnds.EveryTick,
    C3.Plugins.System.Cnds.Compare,
    C3.Behaviors.EightDir.Acts.SimulateControl,
    C3.Plugins.LocalStorage.Cnds.OnItemGet,
    C3.Plugins.System.Exps.int,
    C3.Plugins.LocalStorage.Exps.ItemValue,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Behaviors.Tween.Cnds.IsPlaying,
    C3.Plugins.Spritefont2.Exps.Y,
    C3.Plugins.Sprite.Cnds.IsVisible,
    C3.Behaviors.Timer.Cnds.OnTimer,
    C3.Plugins.System.Acts.SubVar,
    C3.Behaviors.Timer.Acts.StopTimer,
    C3.Behaviors.scrollto.Acts.Shake,
    C3.Plugins.Sprite.Cnds.IsOutsideLayout,
    C3.Plugins.Spritefont2.Exps.X,
    C3.Plugins.Sprite.Acts.MoveToBottom,
    C3.Behaviors.Timer.Cnds.IsTimerPaused,
    C3.Plugins.System.Exps.dt,
    C3.Behaviors.Tween.Cnds.IsAnyPlaying,
    C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
    C3.Behaviors.Bullet.Acts.SetEnabled,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.Keyboard.Cnds.OnKey,
    C3.Plugins.Touch.Exps.SpeedAt,
    C3.Plugins.System.Cnds.IsBetweenAngles,
    C3.Plugins.Touch.Exps.AngleAt,
    C3.Plugins.Touch.Cnds.OnTapGestureObject,
    C3.Plugins.System.Acts.GoToLayout,
    C3.ScriptsInEvents.Game_Event118_Act1,
    C3.Plugins.Sprite.Cnds.CompareFrame,
    C3.Behaviors.Tween.Cnds.OnTweensFinished,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Plugins.System.Cnds.ForEach,
    C3.Plugins.System.Acts.RestartLayout,
    C3.Plugins.System.Cnds.CompareBoolVar,
    C3.ScriptsInEvents.Game_Event146_Act1,
    C3.ScriptsInEvents.Game_Event154_Act4,
    C3.Behaviors.Timer.Acts.PauseResumeTimer,
    C3.ScriptsInEvents.Game_Event160_Act1,
    C3.Plugins.System.Cnds.For,
    C3.Plugins.advert.Acts.HideBanner,
    C3.Plugins.advert.Acts.CreateBanner,
    C3.Plugins.advert.Cnds.IsShowingBanner,
    C3.Plugins.advert.Acts.ShowBanner,
    C3.Plugins.Sprite.Acts.SetSize,
    C3.Plugins.Sprite.Exps.Width,
    C3.Plugins.Sprite.Exps.Height,
    C3.Plugins.Audio.Cnds.IsTagPlaying,
    C3.Plugins.Audio.Acts.Stop,
    C3.Plugins.Mouse.Acts.SetCursor,
    C3.Plugins.Mouse.Exps.X,
    C3.Plugins.Mouse.Exps.Y,
    C3.Plugins.Mouse.Cnds.OnClick,
    C3.Plugins.Sprite.Acts.SetX,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.LocalStorage.Cnds.OnItemMissing,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.Sprite.Cnds.PickChildren,
    C3.Plugins.Sprite.Cnds.CompareInstanceVar,
    C3.Behaviors.MoveTo.Acts.MoveToPosition,
    C3.Behaviors.MoveTo.Acts.SetEnabled,
    C3.Behaviors.MoveTo.Cnds.OnArrived,
    C3.Plugins.Sprite.Exps.ChildCount,
    C3.Plugins.advert.Acts.CreateInterstitial,
    C3.Plugins.advert.Cnds.OnInterstitialComplete,
    C3.Plugins.advert.Cnds.OnInterstitialFailedToLoad,
    C3.Plugins.advert.Cnds.IsShowingInterstitial,
    C3.Plugins.advert.Cnds.IsInterstitialLoaded,
    C3.Plugins.System.Cnds.TriggerOnce,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.System.Acts.WaitForPreviousActions,
    C3.Plugins.advert.Acts.ShowInterstitial,
    C3.Plugins.Text.Acts.Destroy,
  ];
};
self.C3_JsPropNameTable = [
  { locked: 0 },
  { id: 0 },
  { junglegate: 0 },
  { junglebg: 0 },
  { beachbg: 0 },
  { beachgate: 0 },
  { IcyCaveBg: 0 },
  { IcyCavegate: 0 },
  { icyPRT: 0 },
  { oceanbg: 0 },
  { oceangate: 0 },
  { pumpkinbg: 0 },
  { pumpkingate: 0 },
  { castlewhee: 0 },
  { castlebg: 0 },
  { castlegate: 0 },
  { index: 0 },
  { Pin: 0 },
  { attacher: 0 },
  { MoveTo: 0 },
  { blue: 0 },
  { cellId: 0 },
  { Tween: 0 },
  { Bullet: 0 },
  { food: 0 },
  { "8Direction": 0 },
  { green: 0 },
  { Keyboard: 0 },
  { snakebody: 0 },
  { bodycount: 0 },
  { Solid: 0 },
  { snakemouthopen: 0 },
  { snaketail: 0 },
  { tail: 0 },
  { snakebody2: 0 },
  { ScrollTo: 0 },
  { shaker: 0 },
  { foodCollider: 0 },
  { boundary: 0 },
  { Timer: 0 },
  { timerTxt: 0 },
  { collider: 0 },
  { scoreTxt: 0 },
  { pointTxt: 0 },
  { keyTxt: 0 },
  { overlay: 0 },
  { leveltxt: 0 },
  { overlay2: 0 },
  { mover: 0 },
  { highscoreTxt: 0 },
  { collider2: 0 },
  { splash_bg: 0 },
  { splash_apple: 0 },
  { splash_grass: 0 },
  { splash_snake: 0 },
  { tear1: 0 },
  { Sine: 0 },
  { title: 0 },
  { enabled: 0 },
  { btnplay: 0 },
  { soundBtn: 0 },
  { btnhowtoplay: 0 },
  { btnmap: 0 },
  { Sine2: 0 },
  { tears: 0 },
  { tears2: 0 },
  { score: 0 },
  { timer: 0 },
  { keycounter: 0 },
  { Touch: 0 },
  { key: 0 },
  { Rotate: 0 },
  { keyhighlight: 0 },
  { awesomepop: 0 },
  { startmessage: 0 },
  { gatearrow: 0 },
  { lifelose: 0 },
  { life: 0 },
  { istockphoto809856984612x: 0 },
  { timeuppopup: 0 },
  { btntryagain: 0 },
  { LocalStorage: 0 },
  { newlevel: 0 },
  { btngogame: 0 },
  { map: 0 },
  { snakemouthclose: 0 },
  { waypoint: 0 },
  { levelNo: 0 },
  { map_btn: 0 },
  { ang: 0 },
  { snakeposObj: 0 },
  { mapcloseBtn: 0 },
  { Audio: 0 },
  { Howtoplay: 0 },
  { instClosebtn: 0 },
  { level: 0 },
  { gateArray: 0 },
  { Blue_1_cry2: 0 },
  { iceparticles: 0 },
  { maplock: 0 },
  { btnhome: 0 },
  { btnpause: 0 },
  { pausedmsg: 0 },
  { spawngrid: 0 },
  { empty: 0 },
  { row: 0 },
  { col: 0 },
  { spawncell: 0 },
  { compassbg: 0 },
  { compassarrow: 0 },
  { compasstop: 0 },
  { SuperTongue: 0 },
  { snaketongue: 0 },
  { circularbar: 0 },
  { leaf: 0 },
  { Particles: 0 },
  { pumpkinleaf: 0 },
  { pumpkinPRT: 0 },
  { beachPRT: 0 },
  { beachflower: 0 },
  { Particles3: 0 },
  { bubble: 0 },
  { castleparticle: 0 },
  { castlePRT: 0 },
  { congrats: 0 },
  { btnhome2: 0 },
  { handicon: 0 },
  { Mouse: 0 },
  { apple_anim: 0 },
  { snake_anim: 0 },
  { MobileAdvert: 0 },
  { JSON: 0 },
  { AJAX: 0 },
  { adl_update_available: 0 },
  { v: 0 },
  { adl_version_shower: 0 },
  { adl_Text2: 0 },
  { adl_loading_Text: 0 },
  { adl_loadingadtext: 0 },
  { adl_white_back: 0 },
  { adl_update_button: 0 },
  { adl_installgamebutton: 0 },
  { adl_blocker: 0 },
  { adl_loading_logo_rotate: 0 },
  { adl_separater: 0 },
  { adl_back: 0 },
  { Browser: 0 },
  { buttons: 0 },
  { gates: 0 },
  { MAX_INDEX: 0 },
  { dir: 0 },
  { levelscore: 0 },
  { totalscore: 0 },
  { keytograb: 0 },
  { sublevel: 0 },
  { keygrabbed: 0 },
  { lives: 0 },
  { highscore: 0 },
  { keysspawned: 0 },
  { sorted: 0 },
  { spawnKeyInterval: 0 },
  { lastdir: 0 },
  { levelover: 0 },
  { collided: 0 },
  { dirstr: 0 },
  { superTongueInterval: 0 },
  { supertongueStayTime: 0 },
  { tempX: 0 },
  { tempY: 0 },
  { rand: 0 },
  { a: 0 },
  { progress: 0 },
  { attacherId: 0 },
  { snakebodyid: 0 },
  { instructions: 0 },
  { audio: 0 },
  { totalopenedLevel: 0 },
  { ismapOpen: 0 },
  { moveindex: 0 },
  { world: 0 },
  { interstitial_ad: 0 },
  { banner_ad: 0 },
  { ad_frequency: 0 },
  { ad_screen_count: 0 },
];

self.InstanceType = {
  junglegate: class extends self.ISpriteInstance {},
  junglebg: class extends self.ITiledBackgroundInstance {},
  beachbg: class extends self.ITiledBackgroundInstance {},
  beachgate: class extends self.ISpriteInstance {},
  IcyCaveBg: class extends self.ITiledBackgroundInstance {},
  IcyCavegate: class extends self.ISpriteInstance {},
  icyPRT: class extends self.ITiledBackgroundInstance {},
  oceanbg: class extends self.ITiledBackgroundInstance {},
  oceangate: class extends self.ISpriteInstance {},
  pumpkinbg: class extends self.ITiledBackgroundInstance {},
  pumpkingate: class extends self.ISpriteInstance {},
  castlewhee: class extends self.ITiledBackgroundInstance {},
  castlebg: class extends self.ITiledBackgroundInstance {},
  castlegate: class extends self.ISpriteInstance {},
  attacher: class extends self.ISpriteInstance {},
  blue: class extends self.ISpriteInstance {},
  food: class extends self.ISpriteInstance {},
  green: class extends self.ISpriteInstance {},
  Keyboard: class extends self.IInstance {},
  snakebody: class extends self.ISpriteInstance {},
  snakemouthopen: class extends self.ISpriteInstance {},
  snaketail: class extends self.ISpriteInstance {},
  tail: class extends self.ISpriteInstance {},
  snakebody2: class extends self.ISpriteInstance {},
  shaker: class extends self.ISpriteInstance {},
  foodCollider: class extends self.ISpriteInstance {},
  boundary: class extends self.ISpriteInstance {},
  timerTxt: class extends self.ISpriteFontInstance {},
  collider: class extends self.ISpriteInstance {},
  scoreTxt: class extends self.ISpriteFontInstance {},
  pointTxt: class extends self.ISpriteFontInstance {},
  keyTxt: class extends self.ISpriteFontInstance {},
  overlay: class extends self.ISpriteInstance {},
  leveltxt: class extends self.ISpriteFontInstance {},
  overlay2: class extends self.ISpriteInstance {},
  mover: class extends self.ISpriteInstance {},
  highscoreTxt: class extends self.ISpriteFontInstance {},
  collider2: class extends self.ISpriteInstance {},
  splash_bg: class extends self.ITiledBackgroundInstance {},
  splash_apple: class extends self.ISpriteInstance {},
  splash_grass: class extends self.ISpriteInstance {},
  splash_snake: class extends self.ISpriteInstance {},
  tear1: class extends self.IParticlesInstance {},
  title: class extends self.ISpriteInstance {},
  btnplay: class extends self.ISpriteInstance {},
  soundBtn: class extends self.ISpriteInstance {},
  btnhowtoplay: class extends self.ISpriteInstance {},
  btnmap: class extends self.ISpriteInstance {},
  tears: class extends self.ISpriteInstance {},
  tears2: class extends self.ISpriteInstance {},
  score: class extends self.ISpriteInstance {},
  timer: class extends self.ISpriteInstance {},
  keycounter: class extends self.ISpriteInstance {},
  Touch: class extends self.IInstance {},
  key: class extends self.ISpriteInstance {},
  keyhighlight: class extends self.ISpriteInstance {},
  awesomepop: class extends self.ISpriteInstance {},
  startmessage: class extends self.ISpriteInstance {},
  gatearrow: class extends self.ISpriteInstance {},
  lifelose: class extends self.ISpriteInstance {},
  life: class extends self.ISpriteInstance {},
  istockphoto809856984612x: class extends self.ISpriteInstance {},
  timeuppopup: class extends self.ISpriteInstance {},
  btntryagain: class extends self.ISpriteInstance {},
  LocalStorage: class extends self.IInstance {},
  newlevel: class extends self.ISpriteInstance {},
  btngogame: class extends self.ISpriteInstance {},
  map: class extends self.ISpriteInstance {},
  snakemouthclose: class extends self.ISpriteInstance {},
  waypoint: class extends self.ISpriteInstance {},
  map_btn: class extends self.ISpriteInstance {},
  snakeposObj: class extends self.ISpriteInstance {},
  mapcloseBtn: class extends self.ISpriteInstance {},
  Audio: class extends self.IInstance {},
  Howtoplay: class extends self.ISpriteInstance {},
  instClosebtn: class extends self.ISpriteInstance {},
  level: class extends self.ISpriteInstance {},
  gateArray: class extends self.IArrayInstance {},
  Blue_1_cry2: class extends self.ISpriteInstance {},
  iceparticles: class extends self.IParticlesInstance {},
  maplock: class extends self.ISpriteInstance {},
  btnhome: class extends self.ISpriteInstance {},
  btnpause: class extends self.ISpriteInstance {},
  pausedmsg: class extends self.ISpriteInstance {},
  spawngrid: class extends self.ISpriteInstance {},
  spawncell: class extends self.ISpriteInstance {},
  compassbg: class extends self.ISpriteInstance {},
  compassarrow: class extends self.ISpriteInstance {},
  compasstop: class extends self.ISpriteInstance {},
  SuperTongue: class extends self.ISpriteInstance {},
  snaketongue: class extends self.ISpriteInstance {},
  circularbar: class extends self.ISpriteInstance {},
  leaf: class extends self.ISpriteInstance {},
  Particles: class extends self.IParticlesInstance {},
  pumpkinleaf: class extends self.ISpriteInstance {},
  pumpkinPRT: class extends self.IParticlesInstance {},
  beachPRT: class extends self.IParticlesInstance {},
  beachflower: class extends self.ISpriteInstance {},
  Particles3: class extends self.IParticlesInstance {},
  bubble: class extends self.IParticlesInstance {},
  castleparticle: class extends self.ISpriteInstance {},
  castlePRT: class extends self.IParticlesInstance {},
  congrats: class extends self.ISpriteInstance {},
  btnhome2: class extends self.ISpriteInstance {},
  handicon: class extends self.ISpriteInstance {},
  Mouse: class extends self.IInstance {},
  apple_anim: class extends self.ISpriteInstance {},
  snake_anim: class extends self.ISpriteInstance {},
  MobileAdvert: class extends self.IInstance {},
  JSON: class extends self.IJSONInstance {},
  AJAX: class extends self.IInstance {},
  adl_update_available: class extends self.ITextInstance {},
  adl_version_shower: class extends self.ITextInstance {},
  adl_Text2: class extends self.ITextInstance {},
  adl_loading_Text: class extends self.ITextInstance {},
  adl_loadingadtext: class extends self.ITextInstance {},
  adl_white_back: class extends self.ISpriteInstance {},
  adl_update_button: class extends self.ISpriteInstance {},
  adl_installgamebutton: class extends self.ISpriteInstance {},
  adl_blocker: class extends self.ISpriteInstance {},
  adl_loading_logo_rotate: class extends self.ISpriteInstance {},
  adl_separater: class extends self.ISpriteInstance {},
  adl_back: class extends self.ISpriteInstance {},
  Browser: class extends self.IInstance {},
  buttons: class extends self.ISpriteInstance {},
  gates: class extends self.ISpriteInstance {},
};
