const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Behaviors.Tween,
    C3.Behaviors.Physics,
    C3.Behaviors.Rotate,
    C3.Behaviors.LOS,
    C3.Plugins.Text,
    C3.Plugins.Particles,
    C3.Behaviors.Sin,
    C3.Plugins.TiledBg,
    C3.Plugins.Touch,
    C3.Plugins.Keyboard,
    C3.Plugins.PlatformInfo,
    C3.Plugins.LocalStorage,
    C3.Plugins.Audio,
    C3.Plugins.Arr,
    C3.Plugins.AJAX,
    C3.Plugins.Browser,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.AJAX.Acts.RequestFile,
    C3.Plugins.AJAX.Cnds.OnComplete,
    C3.Plugins.Arr.Acts.JSONLoad,
    C3.Plugins.AJAX.Exps.LastData,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.System.Acts.SetVar,
    C3.Plugins.LocalStorage.Exps.ItemValue,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.LocalStorage.Cnds.OnItemMissing,
    C3.Plugins.Audio.Cnds.IsTagPlaying,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.Text.Acts.SetText,
    C3.Plugins.System.Acts.SetLayerVisible,
    C3.Plugins.System.Acts.SetLayerInteractive,
    C3.Plugins.TiledBg.Acts.SetWidth,
    C3.Plugins.System.Exps.tokenat,
    C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
    C3.Plugins.Sprite.Cnds.CompareInstanceVar,
    C3.Plugins.Sprite.Cnds.PickChildren,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Plugins.System.Cnds.Else,
    C3.Plugins.System.Cnds.CompareBoolVar,
    C3.Plugins.System.Cnds.EveryTick,
    C3.Plugins.Touch.Cnds.OnTapGestureObject,
    C3.Behaviors.Tween.Cnds.IsAnyPlaying,
    C3.Behaviors.Tween.Acts.TweenTwoProperties,
    C3.Plugins.Sprite.Acts.SetEffectEnabled,
    C3.Plugins.System.Acts.Wait,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Plugins.Sprite.Cnds.CompareFrame,
    C3.Plugins.System.Acts.SubVar,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.Touch.Cnds.OnTouchObject,
    C3.Plugins.Sprite.Cnds.IsAnimPlaying,
    C3.Plugins.Arr.Acts.SetXY,
    C3.Plugins.Arr.Exps.At,
    C3.Plugins.Sprite.Exps.AnimationFrameCount,
    C3.Behaviors.Sin.Acts.SetEnabled,
    C3.Plugins.Sprite.Acts.SetVisible,
    C3.Plugins.Sprite.Cnds.IsVisible,
    C3.Plugins.Sprite.Cnds.PickParent,
    C3.Plugins.Sprite.Acts.SetAngle,
    C3.Plugins.Sprite.Exps.AnimationFrame,
    C3.Plugins.System.Cnds.ForEach,
    C3.Plugins.Text.Acts.SetOpacity,
    C3.Plugins.Text.Cnds.CompareInstanceVar,
    C3.Plugins.System.Acts.WaitForPreviousActions,
    C3.Plugins.Text.Acts.SetVisible,
    C3.Behaviors.Tween.Acts.TweenOneProperty,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.Audio.Acts.SetVolume,
    C3.Plugins.System.Acts.SetBoolVar,
    C3.Plugins.System.Exps.zeropad,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.Sprite.Acts.SetDefaultColor,
    C3.Plugins.System.Exps.rgbex255,
    C3.Plugins.System.Exps.int,
    C3.Plugins.Sprite.Acts.SetScale,
    C3.Plugins.System.Acts.GoToLayoutByName,
    C3.Behaviors.Tween.Cnds.OnTweensFinished,
    C3.Plugins.Sprite.Cnds.OnCreated,
    C3.Plugins.Sprite.Exps.X,
    C3.Plugins.Sprite.Exps.Y,
    C3.Plugins.Sprite.Acts.SetInstanceVar,
    C3.Plugins.Text.Exps.Y,
    C3.Plugins.Text.Exps.X,
    C3.Plugins.Sprite.Acts.MoveToBottom,
    C3.Plugins.Text.Acts.SetHAlign,
    C3.Plugins.Text.Acts.SetInstanceVar,
    C3.Plugins.System.Cnds.LayerVisible,
    C3.Plugins.Sprite.Exps.BBoxRight,
    C3.Plugins.Sprite.Exps.BBoxBottom,
    C3.Plugins.Sprite.Cnds.OnDestroyed,
    C3.Plugins.Sprite.Exps.BBoxLeft,
    C3.Plugins.Sprite.Exps.BBoxTop,
    C3.Plugins.Sprite.Acts.SetOpacity,
    C3.Plugins.TiledBg.Acts.SetHeight,
    C3.Plugins.Sprite.Acts.SetPos,
    C3.Plugins.System.Acts.SetGroupActive,
    C3.Plugins.Arr.Cnds.CompareXY,
    C3.Plugins.System.Exps.random,
    C3.Behaviors.Rotate.Acts.SetSpeed,
    C3.Behaviors.Physics.Acts.SetLinearDamping,
    C3.Behaviors.LOS.Acts.SetCone,
    C3.Behaviors.LOS.Acts.SetRange,
    C3.Plugins.System.Exps.float,
    C3.Plugins.System.Cnds.Every,
    C3.Plugins.Arr.Acts.SetX,
    C3.Plugins.Arr.Acts.Sort,
    C3.Plugins.Text.Acts.ZMoveToObject,
    C3.Plugins.Particles.Acts.ZMoveToObject,
    C3.Plugins.Particles.Acts.SetAngle,
    C3.Plugins.System.Cnds.Repeat,
    C3.Plugins.Particles.Cnds.OnCreated,
    C3.Plugins.Particles.Acts.SetSpraying,
    C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
    C3.Behaviors.Physics.Acts.SetWorldGravity,
    C3.Behaviors.Physics.Cnds.IsEnabled,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.Sprite.Acts.ZMoveToObject,
    C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
    C3.Plugins.Sprite.Exps.Angle,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Plugins.Sprite.Acts.SetCollisions,
    C3.Plugins.System.Cnds.Compare,
    C3.Plugins.Sprite.Exps.Count,
    C3.Plugins.System.Exps.choose,
    C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
    C3.Plugins.Sprite.Acts.AddInstanceVar,
    C3.Plugins.Touch.Cnds.IsInTouch,
    C3.Plugins.Touch.Cnds.OnTouchEnd,
    C3.Plugins.Touch.Exps.X,
    C3.Plugins.Touch.Exps.Y,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.Keyboard.Cnds.IsKeyDown,
    C3.Plugins.Keyboard.Cnds.OnKeyReleased,
    C3.Behaviors.LOS.Cnds.HasLOSToObject,
  ];
};
self.C3_JsPropNameTable = [
  { timer_to_score: 0 },
  { timer_to_minus_score: 0 },
  { Tween: 0 },
  { Physics: 0 },
  { Rotate: 0 },
  { player_1: 0 },
  { AI: 0 },
  { timer_action: 0 },
  { cd_action: 0 },
  { LineOfSight: 0 },
  { player_2: 0 },
  { player_4: 0 },
  { player_3: 0 },
  { bg_pause: 0 },
  { id: 0 },
  { tx_character: 0 },
  { tx_result: 0 },
  { win_part: 0 },
  { Sine: 0 },
  { Sine2: 0 },
  { confetti: 0 },
  { tx_limit_map: 0 },
  { panel_limit_map: 0 },
  { icon_plus_minus_score: 0 },
  { max_spawner_players: 0 },
  { min_spawner_players: 0 },
  { icon_hp: 0 },
  { bg_tb: 0 },
  { bg_obj: 0 },
  { move_part: 0 },
  { trampoline_part: 0 },
  { id_state: 0 },
  { cd_switch_pos: 0 },
  { trampoline: 0 },
  { count_trampoline: 0 },
  { timer: 0 },
  { timer_switch_pos: 0 },
  { spawner_trampoline: 0 },
  { wall: 0 },
  { light_circle: 0 },
  { Touch: 0 },
  { Keyboard: 0 },
  { PlatformInfo: 0 },
  { LocalStorage: 0 },
  { Audio: 0 },
  { array_player_data: 0 },
  { AJAX: 0 },
  { Browser: 0 },
  { b_sound: 0 },
  { b_restart: 0 },
  { b_menu: 0 },
  { b_music: 0 },
  { b_start_game: 0 },
  { b_pause: 0 },
  { b_resume: 0 },
  { b_change_score: 0 },
  { b_result: 0 },
  { b_change_limit: 0 },
  { tx_buttons: 0 },
  { transition_obj: 0 },
  { transition_bg: 0 },
  { id_player: 0 },
  { character_icon: 0 },
  { b_select_type_character: 0 },
  { b_delete_character: 0 },
  { bg_menu_obj: 0 },
  { tb_menu_bg: 0 },
  { tb_menu_bg_2: 0 },
  { sky: 0 },
  { icon_hint: 0 },
  { id_mode: 0 },
  { tx_mode: 0 },
  { tx_best_score: 0 },
  { bg_select_mode: 0 },
  { hint: 0 },
  { tx_hint_mode: 0 },
  { tx_limit: 0 },
  { tx_set_limit: 0 },
  { icon_set_score: 0 },
  { bg_icon_pause: 0 },
  { array_timer_limit: 0 },
  { sound: 0 },
  { music: 0 },
  { isMobile: 0 },
  { transition: 0 },
  { transition_bg_color: 0 },
  { transiotion_sprite: 0 },
  { transition_sprite_angle: 0 },
  { id_limit: 0 },
  { max_score_compentitive: 0 },
  { max_time_compentitive: 0 },
  { cd_time_compentitive: 0 },
  { score: 0 },
  { best_score: 0 },
  { hp_classic: 0 },
  { go_to: 0 },
  { isPlayer: 0 },
  { x_pos: 0 },
  { y_pos: 0 },
  { type: 0 },
  { id_character: 0 },
  { game: 0 },
  { hp_players: 0 },
  { speed_rotate: 0 },
  { power_move: 0 },
  { linear_damping: 0 },
  { wall_power: 0 },
  { power_impulse_player: 0 },
  { timer_to_give_score: 0 },
  { timer_to_switch_pos: 0 },
  { cone_view_bot: 0 },
  { range_view_bot: 0 },
  { min_max_timer_bot: 0 },
  { trampoline_impulse: 0 },
  { tx: 0 },
  { x_offset: 0 },
  { id_frame: 0 },
];

self.InstanceType = {
  player_1: class extends self.ISpriteInstance {},
  player_2: class extends self.ISpriteInstance {},
  player_4: class extends self.ISpriteInstance {},
  player_3: class extends self.ISpriteInstance {},
  bg_pause: class extends self.ISpriteInstance {},
  tx_character: class extends self.ITextInstance {},
  tx_result: class extends self.ITextInstance {},
  win_part: class extends self.IParticlesInstance {},
  confetti: class extends self.ISpriteInstance {},
  tx_limit_map: class extends self.ITextInstance {},
  panel_limit_map: class extends self.ISpriteInstance {},
  icon_plus_minus_score: class extends self.ISpriteInstance {},
  max_spawner_players: class extends self.ISpriteInstance {},
  min_spawner_players: class extends self.ISpriteInstance {},
  icon_hp: class extends self.ISpriteInstance {},
  bg_tb: class extends self.ITiledBackgroundInstance {},
  bg_obj: class extends self.ISpriteInstance {},
  move_part: class extends self.ISpriteInstance {},
  trampoline_part: class extends self.ISpriteInstance {},
  trampoline: class extends self.ISpriteInstance {},
  spawner_trampoline: class extends self.ISpriteInstance {},
  wall: class extends self.ISpriteInstance {},
  light_circle: class extends self.ISpriteInstance {},
  Touch: class extends self.IInstance {},
  Keyboard: class extends self.IInstance {},
  PlatformInfo: class extends self.IInstance {},
  LocalStorage: class extends self.IInstance {},
  Audio: class extends self.IInstance {},
  array_player_data: class extends self.IArrayInstance {},
  AJAX: class extends self.IInstance {},
  Browser: class extends self.IInstance {},
  b_sound: class extends self.ISpriteInstance {},
  b_restart: class extends self.ISpriteInstance {},
  b_menu: class extends self.ISpriteInstance {},
  b_music: class extends self.ISpriteInstance {},
  b_start_game: class extends self.ISpriteInstance {},
  b_pause: class extends self.ISpriteInstance {},
  b_resume: class extends self.ISpriteInstance {},
  b_change_score: class extends self.ISpriteInstance {},
  b_result: class extends self.ISpriteInstance {},
  b_change_limit: class extends self.ISpriteInstance {},
  tx_buttons: class extends self.ITextInstance {},
  transition_obj: class extends self.ISpriteInstance {},
  transition_bg: class extends self.ISpriteInstance {},
  character_icon: class extends self.ISpriteInstance {},
  b_select_type_character: class extends self.ISpriteInstance {},
  b_delete_character: class extends self.ISpriteInstance {},
  bg_menu_obj: class extends self.ISpriteInstance {},
  tb_menu_bg: class extends self.ITiledBackgroundInstance {},
  tb_menu_bg_2: class extends self.ITiledBackgroundInstance {},
  sky: class extends self.ISpriteInstance {},
  icon_hint: class extends self.ISpriteInstance {},
  tx_mode: class extends self.ITextInstance {},
  tx_best_score: class extends self.ITextInstance {},
  bg_select_mode: class extends self.ISpriteInstance {},
  tx_hint_mode: class extends self.ITextInstance {},
  tx_limit: class extends self.ITextInstance {},
  tx_set_limit: class extends self.ITextInstance {},
  icon_set_score: class extends self.ISpriteInstance {},
  bg_icon_pause: class extends self.ISpriteInstance {},
  array_timer_limit: class extends self.IArrayInstance {},
};
