const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Plugins.Touch,
    C3.Behaviors.Bullet,
    C3.Behaviors.Platform,
    C3.Plugins.Text,
    C3.Plugins.LocalStorage,
    C3.Plugins.Audio,
    C3.Behaviors.Sin,
    C3.Behaviors.Rotate,
    C3.Plugins.advert,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.Touch.Cnds.OnTapGestureObject,
    C3.Plugins.System.Acts.GoToLayout,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.LocalStorage.Acts.GetItem,
    C3.Plugins.LocalStorage.Cnds.OnItemGet,
    C3.Plugins.LocalStorage.Cnds.CompareValue,
    C3.Plugins.System.Acts.SetVar,
    C3.Plugins.LocalStorage.Exps.ItemValue,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.Audio.Cnds.IsTagPlaying,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.System.Cnds.Else,
    C3.Plugins.Touch.Cnds.OnTouchObject,
    C3.Plugins.Audio.Acts.SetMasterVolume,
    C3.Plugins.System.Exps.layoutname,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.System.Acts.SubVar,
    C3.Plugins.System.Cnds.EveryTick,
    C3.Plugins.Text.Acts.SetText,
    C3.Behaviors.Platform.Acts.SetVectorX,
    C3.Plugins.System.Cnds.LayerVisible,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.System.Cnds.TriggerOnce,
    C3.Plugins.System.Acts.SetLayerVisible,
    C3.Plugins.System.Acts.SetLayerInteractive,
    C3.Plugins.System.Cnds.Compare,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Plugins.advert.Cnds.IsInterstitialLoaded,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.System.Acts.Wait,
    C3.Plugins.System.Acts.WaitForPreviousActions,
    C3.Plugins.advert.Acts.ShowInterstitial,
    C3.Plugins.Text.Acts.Destroy,
    C3.Plugins.advert.Acts.CreateInterstitial,
    C3.Plugins.advert.Cnds.OnInterstitialComplete,
    C3.Plugins.advert.Cnds.OnInterstitialFailedToLoad,
    C3.Plugins.advert.Cnds.IsShowingInterstitial,
  ];
};
self.C3_JsPropNameTable = [
  { levels: 0 },
  { Play_Btn: 0 },
  { Touch: 0 },
  { levelsSelectBackground: 0 },
  { levelLock2: 0 },
  { levelLock3: 0 },
  { level_6_10_Txt: 0 },
  { levelUnlock: 0 },
  { background: 0 },
  { player: 0 },
  { shootCount: 0 },
  { SelectLevel: 0 },
  { LevelNum_1: 0 },
  { Bullet: 0 },
  { Arrow: 0 },
  { Platform: 0 },
  { zombie: 0 },
  { zombie2: 0 },
  { Pause_Popup: 0 },
  { Pause_ResumeBtn: 0 },
  { home2: 0 },
  { gameOver: 0 },
  { GO_RestartBtn: 0 },
  { GO_HomeBtn: 0 },
  { LevelComplete2: 0 },
  { LC_HomeBtn: 0 },
  { LC_NextBtn: 0 },
  { BulletCount_Txt: 0 },
  { line: 0 },
  { zombie6: 0 },
  { zombie7: 0 },
  { zombie8: 0 },
  { zombie3: 0 },
  { zombie4: 0 },
  { zombie5: 0 },
  { zombie9: 0 },
  { zombie10: 0 },
  { zombie11: 0 },
  { zombie12: 0 },
  { zombie13: 0 },
  { zombie14: 0 },
  { zombie15: 0 },
  { zombie16: 0 },
  { zombie17: 0 },
  { zombie18: 0 },
  { levelComplet: 0 },
  { zombie19: 0 },
  { LocalStorage: 0 },
  { background_6_10: 0 },
  { zombie20: 0 },
  { zombie21: 0 },
  { zombie22: 0 },
  { zombie23: 0 },
  { zombie24: 0 },
  { zombie25: 0 },
  { zombie26: 0 },
  { zombie27: 0 },
  { zombie28: 0 },
  { zombie29: 0 },
  { zombie30: 0 },
  { zombie31: 0 },
  { zombie32: 0 },
  { zombie33: 0 },
  { zombie34: 0 },
  { zombie35: 0 },
  { zombie36: 0 },
  { zombie37: 0 },
  { zombie38: 0 },
  { background7: 0 },
  { zombie888: 0 },
  { zombie40: 0 },
  { TextText1235: 0 },
  { zombie41: 0 },
  { zombie42: 0 },
  { Text2: 0 },
  { zombie43: 0 },
  { zombie44: 0 },
  { zombie45: 0 },
  { zombie46: 0 },
  { zombie47: 0 },
  { zombie48: 0 },
  { zombie49: 0 },
  { zombie50: 0 },
  { zombie51: 0 },
  { zombie52: 0 },
  { stop2: 0 },
  { Audio: 0 },
  { level_1_5_Txt: 0 },
  { level_11_15_Txt: 0 },
  { back: 0 },
  { SoundOn: 0 },
  { Blur: 0 },
  { Sine: 0 },
  { gameName2: 0 },
  { v: 0 },
  { adl_version_shower: 0 },
  { adl_Text2: 0 },
  { adl_loading_Text: 0 },
  { adl_loadingadtext: 0 },
  { adl_back: 0 },
  { adl_white_back: 0 },
  { adl_blocker: 0 },
  { Rotate: 0 },
  { adl_loading_logo_rotate: 0 },
  { adl_separater: 0 },
  { MobileAdvert: 0 },
  { LEVEL: 0 },
  { sound: 0 },
  { Life2: 0 },
  { bullet: 0 },
  { Life: 0 },
  { LevelNumber: 0 },
  { Life4: 0 },
  { Life5: 0 },
  { Life6: 0 },
  { bullet2: 0 },
  { Life7: 0 },
  { Life8: 0 },
  { Life9: 0 },
  { Bullet3: 0 },
  { Life10: 0 },
  { Life11: 0 },
  { Life12: 0 },
  { Life13: 0 },
  { Life14: 0 },
  { Bullet4: 0 },
  { Life15: 0 },
  { Life16: 0 },
  { Life17: 0 },
  { Life18: 0 },
  { Life19: 0 },
  { Life20: 0 },
  { bullet5: 0 },
  { Life21: 0 },
  { Life22: 0 },
  { Life23: 0 },
  { Life24: 0 },
  { Life25: 0 },
  { bullet6: 0 },
  { Bullet7: 0 },
  { Life26: 0 },
  { Life27: 0 },
  { Life28: 0 },
  { Life29: 0 },
  { Life30: 0 },
  { Bullet8: 0 },
  { Life31: 0 },
  { Life32: 0 },
  { Life33: 0 },
  { Life34: 0 },
  { Life35: 0 },
  { Life36: 0 },
  { Bullet9: 0 },
  { Life37: 0 },
  { Life38: 0 },
  { Life39: 0 },
  { Life40: 0 },
  { Life41: 0 },
  { Life42: 0 },
  { Bullet10: 0 },
  { Life43: 0 },
  { Life44: 0 },
  { Life45: 0 },
  { Life46: 0 },
  { Life47: 0 },
  { Life48: 0 },
  { Bullet11: 0 },
  { Life49: 0 },
  { Life50: 0 },
  { Life51: 0 },
  { Life52: 0 },
  { Life53: 0 },
  { Life54: 0 },
  { Bullet12: 0 },
  { Life55: 0 },
  { Life56: 0 },
  { Life57: 0 },
  { Life58: 0 },
  { Life59: 0 },
  { Life60: 0 },
  { Life61: 0 },
  { Bullet13: 0 },
  { Life62: 0 },
  { Life63: 0 },
  { Life64: 0 },
  { Life65: 0 },
  { Life66: 0 },
  { Life67: 0 },
  { Life68: 0 },
  { Life69: 0 },
  { Bullet14: 0 },
  { Life70: 0 },
  { Life71: 0 },
  { Life72: 0 },
  { Life73: 0 },
  { Life75: 0 },
  { Life76: 0 },
  { Life77: 0 },
  { Bullet15: 0 },
  { Life78: 0 },
  { Life79: 0 },
  { Life80: 0 },
  { Life81: 0 },
  { Life82: 0 },
  { Life83: 0 },
  { Life84: 0 },
  { Life85: 0 },
  { Life86: 0 },
  { Life87: 0 },
  { interstitial_ad: 0 },
  { banner_ad: 0 },
  { ad_frequency: 0 },
  { ad_screen_count: 0 },
];

self.InstanceType = {
  levels: class extends self.ISpriteInstance {},
  Play_Btn: class extends self.ISpriteInstance {},
  Touch: class extends self.IInstance {},
  levelsSelectBackground: class extends self.ISpriteInstance {},
  levelLock2: class extends self.ISpriteInstance {},
  levelLock3: class extends self.ISpriteInstance {},
  level_6_10_Txt: class extends self.ISpriteInstance {},
  levelUnlock: class extends self.ISpriteInstance {},
  background: class extends self.ISpriteInstance {},
  player: class extends self.ISpriteInstance {},
  shootCount: class extends self.ISpriteInstance {},
  SelectLevel: class extends self.ISpriteInstance {},
  LevelNum_1: class extends self.ISpriteInstance {},
  Arrow: class extends self.ISpriteInstance {},
  zombie: class extends self.ISpriteInstance {},
  zombie2: class extends self.ISpriteInstance {},
  Pause_Popup: class extends self.ISpriteInstance {},
  Pause_ResumeBtn: class extends self.ISpriteInstance {},
  home2: class extends self.ISpriteInstance {},
  gameOver: class extends self.ISpriteInstance {},
  GO_RestartBtn: class extends self.ISpriteInstance {},
  GO_HomeBtn: class extends self.ISpriteInstance {},
  LevelComplete2: class extends self.ISpriteInstance {},
  LC_HomeBtn: class extends self.ISpriteInstance {},
  LC_NextBtn: class extends self.ISpriteInstance {},
  BulletCount_Txt: class extends self.ITextInstance {},
  line: class extends self.ISpriteInstance {},
  zombie6: class extends self.ISpriteInstance {},
  zombie7: class extends self.ISpriteInstance {},
  zombie8: class extends self.ISpriteInstance {},
  zombie3: class extends self.ISpriteInstance {},
  zombie4: class extends self.ISpriteInstance {},
  zombie5: class extends self.ISpriteInstance {},
  zombie9: class extends self.ISpriteInstance {},
  zombie10: class extends self.ISpriteInstance {},
  zombie11: class extends self.ISpriteInstance {},
  zombie12: class extends self.ISpriteInstance {},
  zombie13: class extends self.ISpriteInstance {},
  zombie14: class extends self.ISpriteInstance {},
  zombie15: class extends self.ISpriteInstance {},
  zombie16: class extends self.ISpriteInstance {},
  zombie17: class extends self.ISpriteInstance {},
  zombie18: class extends self.ISpriteInstance {},
  zombie19: class extends self.ISpriteInstance {},
  LocalStorage: class extends self.IInstance {},
  background_6_10: class extends self.ISpriteInstance {},
  zombie20: class extends self.ISpriteInstance {},
  zombie21: class extends self.ISpriteInstance {},
  zombie22: class extends self.ISpriteInstance {},
  zombie23: class extends self.ISpriteInstance {},
  zombie24: class extends self.ISpriteInstance {},
  zombie25: class extends self.ISpriteInstance {},
  zombie26: class extends self.ISpriteInstance {},
  zombie27: class extends self.ISpriteInstance {},
  zombie28: class extends self.ISpriteInstance {},
  zombie29: class extends self.ISpriteInstance {},
  zombie30: class extends self.ISpriteInstance {},
  zombie31: class extends self.ISpriteInstance {},
  zombie32: class extends self.ISpriteInstance {},
  zombie33: class extends self.ISpriteInstance {},
  zombie34: class extends self.ISpriteInstance {},
  zombie35: class extends self.ISpriteInstance {},
  zombie36: class extends self.ISpriteInstance {},
  zombie37: class extends self.ISpriteInstance {},
  zombie38: class extends self.ISpriteInstance {},
  background7: class extends self.ISpriteInstance {},
  zombie888: class extends self.ISpriteInstance {},
  zombie40: class extends self.ISpriteInstance {},
  TextText1235: class extends self.ITextInstance {},
  zombie41: class extends self.ISpriteInstance {},
  zombie42: class extends self.ISpriteInstance {},
  Text2: class extends self.ITextInstance {},
  zombie43: class extends self.ISpriteInstance {},
  zombie44: class extends self.ISpriteInstance {},
  zombie45: class extends self.ISpriteInstance {},
  zombie46: class extends self.ISpriteInstance {},
  zombie47: class extends self.ISpriteInstance {},
  zombie48: class extends self.ISpriteInstance {},
  zombie49: class extends self.ISpriteInstance {},
  zombie50: class extends self.ISpriteInstance {},
  zombie51: class extends self.ISpriteInstance {},
  zombie52: class extends self.ISpriteInstance {},
  stop2: class extends self.ISpriteInstance {},
  Audio: class extends self.IInstance {},
  level_1_5_Txt: class extends self.ISpriteInstance {},
  level_11_15_Txt: class extends self.ISpriteInstance {},
  back: class extends self.ISpriteInstance {},
  SoundOn: class extends self.ISpriteInstance {},
  Blur: class extends self.ISpriteInstance {},
  gameName2: class extends self.ISpriteInstance {},
  adl_version_shower: class extends self.ITextInstance {},
  adl_Text2: class extends self.ITextInstance {},
  adl_loading_Text: class extends self.ITextInstance {},
  adl_loadingadtext: class extends self.ITextInstance {},
  adl_back: class extends self.ISpriteInstance {},
  adl_white_back: class extends self.ISpriteInstance {},
  adl_blocker: class extends self.ISpriteInstance {},
  adl_loading_logo_rotate: class extends self.ISpriteInstance {},
  adl_separater: class extends self.ISpriteInstance {},
  MobileAdvert: class extends self.IInstance {},
};
