const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Behaviors.Tween,
    C3.Behaviors.Fade,
    C3.Behaviors.LOS,
    C3.Behaviors.Sin,
    C3.Plugins.Particles,
    C3.Behaviors.Pin,
    C3.Plugins.TiledBg,
    C3.Plugins.Spritefont2,
    C3.Behaviors.jumpthru,
    C3.Behaviors.scrollto,
    C3.Behaviors.Bullet,
    C3.Behaviors.solid,
    C3.Behaviors.Platform,
    C3.Plugins.Arr,
    C3.Plugins.Audio,
    C3.Plugins.Keyboard,
    C3.Plugins.LocalStorage,
    C3.Plugins.Mouse,
    C3.Plugins.PlatformInfo,
    C3.Plugins.Timeline,
    C3.Plugins.Touch,
    C3.Behaviors.wrap,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.Particles.Acts.Destroy,
    C3.Plugins.Spritefont2.Acts.SetText,
    C3.Plugins.System.Exps.layoutname,
    C3.Plugins.System.Acts.SetVar,
    C3.Plugins.System.Exps.int,
    C3.Plugins.System.Acts.SetBoolVar,
    C3.Plugins.Spritefont2.Acts.SetVisible,
    C3.Plugins.Spritefont2.Acts.Destroy,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Plugins.Arr.Cnds.CompareXY,
    C3.Plugins.Sprite.Acts.SetOpacity,
    C3.Plugins.Sprite.Acts.SetVisible,
    C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
    C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
    C3.Plugins.System.Acts.SetGroupActive,
    C3.Plugins.System.Cnds.EveryTick,
    C3.Plugins.Sprite.Acts.SetPos,
    C3.Plugins.Sprite.Exps.X,
    C3.Plugins.Sprite.Exps.Y,
    C3.Behaviors.Platform.Acts.SetJumpStrength,
    C3.Behaviors.Pin.Acts.PinByProperties,
    C3.Plugins.System.Acts.Wait,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.Sprite.Cnds.OnAnimFinished,
    C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
    C3.Plugins.Sprite.Cnds.IsAnimPlaying,
    C3.Plugins.Keyboard.Cnds.OnKey,
    C3.Plugins.Touch.Cnds.OnTouchObject,
    C3.Plugins.Sprite.Acts.SetInstanceVar,
    C3.Behaviors.Platform.Acts.SimulateControl,
    C3.Plugins.Touch.Cnds.IsTouchingObject,
    C3.Plugins.System.Cnds.Else,
    C3.Plugins.Keyboard.Cnds.IsKeyDown,
    C3.Behaviors.Platform.Cnds.IsOnFloor,
    C3.Plugins.Keyboard.Cnds.OnKeyReleased,
    C3.Plugins.Touch.Cnds.OnTouchEnd,
    C3.Plugins.System.Cnds.TriggerOnce,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.Spritefont2.Acts.SetInstanceVar,
    C3.Plugins.Spritefont2.Acts.SetOpacity,
    C3.Behaviors.Fade.Acts.RestartFade,
    C3.Behaviors.Platform.Cnds.OnLand,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.Sprite.Acts.SetAngle,
    C3.Plugins.Sprite.Exps.Angle,
    C3.Behaviors.Fade.Acts.StartFade,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.Spritefont2.Exps.X,
    C3.Plugins.Spritefont2.Exps.Y,
    C3.Behaviors.Tween.Acts.TweenValue,
    C3.Plugins.System.Exps.zeropad,
    C3.Behaviors.Tween.Acts.TweenTwoProperties,
    C3.Behaviors.scrollto.Acts.Shake,
    C3.Behaviors.Tween.Acts.TweenOneProperty,
    C3.Plugins.Audio.Acts.Stop,
    C3.Plugins.System.Cnds.CompareBoolVar,
    C3.Behaviors.Tween.Acts.StopTweens,
    C3.Plugins.Sprite.Acts.SetEffectParam,
    C3.Behaviors.Platform.Cnds.OnJump,
    C3.Plugins.Sprite.Cnds.CompareInstanceVar,
    C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
    C3.Plugins.Sprite.Exps.ImagePointX,
    C3.Plugins.Sprite.Exps.ImagePointY,
    C3.Plugins.Particles.Acts.SetAngle,
    C3.Plugins.Particles.Acts.MoveToBottom,
    C3.Behaviors.Platform.Cnds.IsJumping,
    C3.Plugins.Sprite.Acts.SetCollisions,
    C3.Behaviors.Platform.Cnds.IsFalling,
    C3.Plugins.Audio.Cnds.IsTagPlaying,
    C3.Behaviors.Tween.Cnds.IsPlaying,
    C3.Plugins.Spritefont2.Acts.SetEffectParam,
    C3.Behaviors.Tween.Exps.Value,
    C3.Behaviors.jumpthru.Acts.SetEnabled,
    C3.Plugins.Sprite.Cnds.CompareFrame,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Behaviors.Platform.Acts.SetVectorY,
    C3.Plugins.Sprite.Cnds.IsOnScreen,
    C3.Behaviors.Bullet.Acts.SetEnabled,
    C3.Plugins.Sprite.Cnds.CompareX,
    C3.Plugins.Sprite.Cnds.IsOutsideLayout,
    C3.Plugins.Sprite.Acts.StopAnim,
    C3.Plugins.Sprite.Acts.StartAnim,
    C3.Plugins.Sprite.Acts.SetHeight,
    C3.Plugins.Sprite.Exps.Height,
    C3.Plugins.System.Cnds.OnLayoutEnd,
    C3.Behaviors.Sin.Acts.SetMagnitude,
    C3.Behaviors.Sin.Acts.SetEnabled,
    C3.Plugins.System.Exps.random,
    C3.Behaviors.Sin.Acts.SetPhase,
    C3.Plugins.Sprite.Acts.MoveToLayer,
    C3.Plugins.System.Exps.canvastolayerx,
    C3.Plugins.System.Exps.layertocanvasx,
    C3.Plugins.System.Exps.layertocanvasy,
    C3.Plugins.System.Exps.canvastolayery,
    C3.Behaviors.Tween.Cnds.OnTweensFinished,
    C3.Plugins.System.Cnds.ForEach,
    C3.Behaviors.LOS.Acts.SetRange,
    C3.Behaviors.LOS.Cnds.HasLOSToObject,
    C3.Plugins.System.Cnds.PickAll,
    C3.Plugins.Sprite.Cnds.CompareOpacity,
    C3.Plugins.Sprite.Exps.AnimationFrame,
    C3.Plugins.Particles.Acts.SetRate,
    C3.Plugins.Arr.Exps.At,
    C3.Plugins.Arr.Acts.SetXY,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.TiledBg.Acts.SetVisible,
    C3.Plugins.Sprite.Acts.SetX,
    C3.Plugins.TiledBg.Cnds.IsVisible,
    C3.Plugins.Audio.Acts.SetPaused,
    C3.Plugins.Audio.Acts.StopAll,
    C3.Behaviors.Tween.Acts.StopAllTweens,
    C3.Behaviors.Platform.Acts.SetEnabled,
    C3.Behaviors.Bullet.Acts.SetSpeed,
    C3.Plugins.System.Acts.RestartLayout,
    C3.Plugins.System.Acts.GoToLayout,
    C3.Plugins.System.Acts.SetTimescale,
    C3.Plugins.System.Cnds.Compare,
    C3.Plugins.System.Acts.GoToLayoutByName,
    C3.Plugins.System.Cnds.Every,
    C3.Plugins.Sprite.Acts.SetMirrored,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.Arr.Exps.AsJSON,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.LocalStorage.Acts.GetItem,
    C3.Plugins.LocalStorage.Cnds.OnItemGet,
    C3.Plugins.Arr.Acts.JSONLoad,
    C3.Plugins.LocalStorage.Exps.ItemValue,
    C3.Plugins.LocalStorage.Cnds.OnItemMissing,
    C3.Plugins.TiledBg.Cnds.CompareOpacity,
    C3.Behaviors.Tween.Cnds.IsAnyPlaying,
    C3.Plugins.Mouse.Cnds.IsOverObject,
    C3.Behaviors.Pin.Acts.Unpin,
    C3.Plugins.System.Acts.SubVar,
    C3.Plugins.LocalStorage.Acts.ClearStorage,
  ];
};
self.C3_JsPropNameTable = [
  { btn_paused: 0 },
  { Tween: 0 },
  { Fade: 0 },
  { btn_forward_ENDGAME: 0 },
  { btn_menu: 0 },
  { btn_menu_ENDGAME: 0 },
  { btn_resume: 0 },
  { btn_retry: 0 },
  { btn_retry_ENDGAME: 0 },
  { btn_StartGame: 0 },
  { btn_audio: 0 },
  { btn_Controls: 0 },
  { btn_grind: 0 },
  { btn_heelflip: 0 },
  { btn_indy: 0 },
  { btn_kickflip: 0 },
  { btn_nosegrind: 0 },
  { btn_noseslide: 0 },
  { btn_ollie: 0 },
  { gotoHUD: 0 },
  { LineOfSight: 0 },
  { coins: 0 },
  { Sine: 0 },
  { combo_letters: 0 },
  { skate_letters: 0 },
  { magnet_item: 0 },
  { Pin: 0 },
  { coins_particles: 0 },
  { magnet_collect_particle: 0 },
  { skate_letters_particles: 0 },
  { spark_particle: 0 },
  { coins_HUD: 0 },
  { combo_letters_HUD: 0 },
  { skate_letters_HUD: 0 },
  { bg_HUD_shadow: 0 },
  { logo_game: 0 },
  { logo_jmneto: 0 },
  { objective_combo_ENDGAME: 0 },
  { objective_score_ENDGAME: 0 },
  { objective_skate_ENDGAME: 0 },
  { panels_endgame: 0 },
  { paused_label: 0 },
  { SF_level_show: 0 },
  { instruction: 0 },
  { tick_score: 0 },
  { SF_bonus: 0 },
  { SF_coins: 0 },
  { SF_combo_WORD_Effect: 0 },
  { SF_label_multiplier: 0 },
  { id: 0 },
  { SF_label_score: 0 },
  { SF_label_score_add: 0 },
  { SF_label_score_add_LOST: 0 },
  { SF_label_score_TWEEN: 0 },
  { SF_target_score_HUD: 0 },
  { label_multiplier_LOST: 0 },
  { name_trick: 0 },
  { label_tricks: 0 },
  { pin_tween_LS: 0 },
  { SF_best_LEVEL_SELECT: 0 },
  { SF_best_score: 0 },
  { SF_labels_ENDGAME: 0 },
  { SF_my_Score: 0 },
  { SF_score_ENDGAME: 0 },
  { btn_credits: 0 },
  { SF_labels_credits: 0 },
  { end_coins_HUD_Tween: 0 },
  { overlap_rail_player: 0 },
  { overlap_ramp: 0 },
  { Jumpthru: 0 },
  { solid_collision: 0 },
  { target_score: 0 },
  { sprite_target_score: 0 },
  { winner_collision: 0 },
  { death_collision: 0 },
  { type: 0 },
  { active: 0 },
  { bonus_collision: 0 },
  { ScrollTo: 0 },
  { camera: 0 },
  { spawn_cars_back: 0 },
  { spawn_cars_front: 0 },
  { bg_game: 0 },
  { bg_houses_tiled: 0 },
  { bg_black_endgame: 0 },
  { bg_menu: 0 },
  { bg_paused: 0 },
  { Fade_INTRO: 0 },
  { Fade_END: 0 },
  { black_transition_fade: 0 },
  { bg_controls: 0 },
  { fog: 0 },
  { alert_plate: 0 },
  { chao: 0 },
  { sidewalk: 0 },
  { stop_plate: 0 },
  { Bullet: 0 },
  { cars_bg: 0 },
  { light_poles: 0 },
  { cars: 0 },
  { cone: 0 },
  { Solid: 0 },
  { ramp: 0 },
  { collision_ON: 0 },
  { rail_small: 0 },
  { trolley: 0 },
  { player_girl_animations: 0 },
  { player_boy_animations: 0 },
  { active_controls: 0 },
  { running: 0 },
  { trick: 0 },
  { on_indy: 0 },
  { Platform: 0 },
  { player_box: 0 },
  { player_afro_animations: 0 },
  { smoke_land: 0 },
  { objective_combo_level_select: 0 },
  { objective_skate_level_select: 0 },
  { level: 0 },
  { skaters_level_select: 0 },
  { objective_score_level_select: 0 },
  { bg_level_select: 0 },
  { btn_arrow_L: 0 },
  { btn_arrow_R: 0 },
  { btn_select_skater: 0 },
  { level_numbers: 0 },
  { skaters_name_label_LS: 0 },
  { tween_levels_A: 0 },
  { tween_levels_B: 0 },
  { tween_levels_C: 0 },
  { afro_selection_panel: 0 },
  { FadeIN: 0 },
  { FadeOUT: 0 },
  { bg_shop: 0 },
  { boy_selection_panel: 0 },
  { btn_back_from_shop: 0 },
  { skater: 0 },
  { btn_buy: 0 },
  { girl_selection_panel: 0 },
  { mark_skater_select: 0 },
  { tween_items_shop: 0 },
  { btn_back_to_menu: 0 },
  { price: 0 },
  { ArrayInfo: 0 },
  { Audio: 0 },
  { Keyboard: 0 },
  { LocalStorage: 0 },
  { Mouse: 0 },
  { PlatformInfo: 0 },
  { TimelineController: 0 },
  { Touch: 0 },
  { black_guy: 0 },
  { boy: 0 },
  { Wrap: 0 },
  { cld1: 0 },
  { cld3: 0 },
  { GAMELAUNCHER: 0 },
  { girl: 0 },
  { Sprite: 0 },
  { Sprite2: 0 },
  { Pin2: 0 },
  { players: 0 },
  { buttons_effect: 0 },
  { rail_collision_ON: 0 },
  { multiplier_COUNT: 0 },
  { audio: 0 },
  { score_add: 0 },
  { score: 0 },
  { coins_magnet_ON: 0 },
  { magnet_distance: 0 },
  { lettersCOMBO: 0 },
  { lettersSKATE: 0 },
  { scoreTARGET: 0 },
  { best_score_levels: 0 },
  { paused: 0 },
  { endGame: 0 },
  { currentLevel: 0 },
  { player_selected: 0 },
  { position_buttons: 0 },
  { LSsave: 0 },
  { LScoins: 0 },
  { LSskaterGIRL: 0 },
  { LSskaterAFRO: 0 },
  { skater_afro_unlock: 0 },
  { skater_girl_unlock: 0 },
];

self.InstanceType = {
  btn_paused: class extends self.ISpriteInstance {},
  btn_forward_ENDGAME: class extends self.ISpriteInstance {},
  btn_menu: class extends self.ISpriteInstance {},
  btn_menu_ENDGAME: class extends self.ISpriteInstance {},
  btn_resume: class extends self.ISpriteInstance {},
  btn_retry: class extends self.ISpriteInstance {},
  btn_retry_ENDGAME: class extends self.ISpriteInstance {},
  btn_StartGame: class extends self.ISpriteInstance {},
  btn_audio: class extends self.ISpriteInstance {},
  btn_Controls: class extends self.ISpriteInstance {},
  btn_grind: class extends self.ISpriteInstance {},
  btn_heelflip: class extends self.ISpriteInstance {},
  btn_indy: class extends self.ISpriteInstance {},
  btn_kickflip: class extends self.ISpriteInstance {},
  btn_nosegrind: class extends self.ISpriteInstance {},
  btn_noseslide: class extends self.ISpriteInstance {},
  btn_ollie: class extends self.ISpriteInstance {},
  coins: class extends self.ISpriteInstance {},
  combo_letters: class extends self.ISpriteInstance {},
  skate_letters: class extends self.ISpriteInstance {},
  magnet_item: class extends self.ISpriteInstance {},
  coins_particles: class extends self.IParticlesInstance {},
  magnet_collect_particle: class extends self.IParticlesInstance {},
  skate_letters_particles: class extends self.IParticlesInstance {},
  spark_particle: class extends self.IParticlesInstance {},
  coins_HUD: class extends self.ISpriteInstance {},
  combo_letters_HUD: class extends self.ISpriteInstance {},
  skate_letters_HUD: class extends self.ISpriteInstance {},
  bg_HUD_shadow: class extends self.ITiledBackgroundInstance {},
  logo_game: class extends self.ISpriteInstance {},
  logo_jmneto: class extends self.ISpriteInstance {},
  objective_combo_ENDGAME: class extends self.ISpriteInstance {},
  objective_score_ENDGAME: class extends self.ISpriteInstance {},
  objective_skate_ENDGAME: class extends self.ISpriteInstance {},
  panels_endgame: class extends self.ISpriteInstance {},
  paused_label: class extends self.ISpriteInstance {},
  SF_level_show: class extends self.ISpriteFontInstance {},
  instruction: class extends self.ISpriteInstance {},
  tick_score: class extends self.ISpriteInstance {},
  SF_bonus: class extends self.ISpriteFontInstance {},
  SF_coins: class extends self.ISpriteFontInstance {},
  SF_combo_WORD_Effect: class extends self.ISpriteFontInstance {},
  SF_label_multiplier: class extends self.ISpriteFontInstance {},
  SF_label_score: class extends self.ISpriteFontInstance {},
  SF_label_score_add: class extends self.ISpriteFontInstance {},
  SF_label_score_add_LOST: class extends self.ISpriteFontInstance {},
  SF_label_score_TWEEN: class extends self.ISpriteFontInstance {},
  SF_target_score_HUD: class extends self.ISpriteFontInstance {},
  label_multiplier_LOST: class extends self.ISpriteFontInstance {},
  label_tricks: class extends self.ISpriteFontInstance {},
  SF_best_LEVEL_SELECT: class extends self.ISpriteFontInstance {},
  SF_best_score: class extends self.ISpriteFontInstance {},
  SF_labels_ENDGAME: class extends self.ISpriteFontInstance {},
  SF_my_Score: class extends self.ISpriteFontInstance {},
  SF_score_ENDGAME: class extends self.ISpriteFontInstance {},
  btn_credits: class extends self.ISpriteFontInstance {},
  SF_labels_credits: class extends self.ISpriteFontInstance {},
  end_coins_HUD_Tween: class extends self.ISpriteInstance {},
  overlap_rail_player: class extends self.ISpriteInstance {},
  overlap_ramp: class extends self.ISpriteInstance {},
  solid_collision: class extends self.ITiledBackgroundInstance {},
  sprite_target_score: class extends self.ISpriteInstance {},
  winner_collision: class extends self.ISpriteInstance {},
  death_collision: class extends self.ISpriteInstance {},
  bonus_collision: class extends self.ISpriteInstance {},
  camera: class extends self.ISpriteInstance {},
  spawn_cars_back: class extends self.ISpriteInstance {},
  spawn_cars_front: class extends self.ISpriteInstance {},
  bg_game: class extends self.ISpriteInstance {},
  bg_houses_tiled: class extends self.ITiledBackgroundInstance {},
  bg_black_endgame: class extends self.ITiledBackgroundInstance {},
  bg_menu: class extends self.ISpriteInstance {},
  bg_paused: class extends self.ITiledBackgroundInstance {},
  black_transition_fade: class extends self.ITiledBackgroundInstance {},
  bg_controls: class extends self.ISpriteInstance {},
  fog: class extends self.ITiledBackgroundInstance {},
  alert_plate: class extends self.ISpriteInstance {},
  chao: class extends self.ITiledBackgroundInstance {},
  sidewalk: class extends self.ITiledBackgroundInstance {},
  stop_plate: class extends self.ISpriteInstance {},
  cars_bg: class extends self.ISpriteInstance {},
  light_poles: class extends self.ISpriteInstance {},
  cars: class extends self.ISpriteInstance {},
  cone: class extends self.ISpriteInstance {},
  ramp: class extends self.ISpriteInstance {},
  rail_small: class extends self.ISpriteInstance {},
  trolley: class extends self.ISpriteInstance {},
  player_girl_animations: class extends self.ISpriteInstance {},
  player_boy_animations: class extends self.ISpriteInstance {},
  player_box: class extends self.ISpriteInstance {},
  player_afro_animations: class extends self.ISpriteInstance {},
  smoke_land: class extends self.ISpriteInstance {},
  objective_combo_level_select: class extends self.ISpriteInstance {},
  objective_skate_level_select: class extends self.ISpriteInstance {},
  level: class extends self.ISpriteInstance {},
  skaters_level_select: class extends self.ISpriteInstance {},
  objective_score_level_select: class extends self.ISpriteInstance {},
  bg_level_select: class extends self.ISpriteInstance {},
  btn_arrow_L: class extends self.ISpriteInstance {},
  btn_arrow_R: class extends self.ISpriteInstance {},
  btn_select_skater: class extends self.ISpriteInstance {},
  level_numbers: class extends self.ISpriteFontInstance {},
  skaters_name_label_LS: class extends self.ISpriteInstance {},
  tween_levels_A: class extends self.ISpriteInstance {},
  tween_levels_B: class extends self.ISpriteInstance {},
  tween_levels_C: class extends self.ISpriteInstance {},
  afro_selection_panel: class extends self.ISpriteInstance {},
  bg_shop: class extends self.ITiledBackgroundInstance {},
  boy_selection_panel: class extends self.ISpriteInstance {},
  btn_back_from_shop: class extends self.ISpriteInstance {},
  btn_buy: class extends self.ISpriteInstance {},
  girl_selection_panel: class extends self.ISpriteInstance {},
  mark_skater_select: class extends self.ISpriteInstance {},
  tween_items_shop: class extends self.ISpriteInstance {},
  btn_back_to_menu: class extends self.ISpriteInstance {},
  price: class extends self.ISpriteInstance {},
  ArrayInfo: class extends self.IArrayInstance {},
  Audio: class extends self.IInstance {},
  Keyboard: class extends self.IInstance {},
  LocalStorage: class extends self.IInstance {},
  Mouse: class extends self.IInstance {},
  PlatformInfo: class extends self.IInstance {},
  TimelineController: class extends self.IInstance {},
  Touch: class extends self.IInstance {},
  black_guy: class extends self.ISpriteInstance {},
  boy: class extends self.ISpriteInstance {},
  cld1: class extends self.ISpriteInstance {},
  cld3: class extends self.ISpriteInstance {},
  GAMELAUNCHER: class extends self.ISpriteInstance {},
  girl: class extends self.ISpriteInstance {},
  Sprite: class extends self.ISpriteInstance {},
  Sprite2: class extends self.ISpriteInstance {},
  players: class extends self.ISpriteInstance {},
  buttons_effect: class extends self.ISpriteInstance {},
};
