const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Behaviors.Fade,
    C3.Plugins.Text,
    C3.Behaviors.Sin,
    C3.Plugins.Touch,
    C3.Plugins.Spritefont2,
    C3.Plugins.Audio,
    C3.Plugins.LocalStorage,
    C3.Plugins.TiledBg,
    C3.Behaviors.Anchor,
    C3.Behaviors.Tween,
    C3.Plugins.Browser,
    C3.Behaviors.Pin,
    C3.Plugins.Keyboard,
    C3.Behaviors.Flash,
    C3.Behaviors.Rotate,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.Audio.Acts.Stop,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.Sprite.Acts.SetVisible,
    C3.Plugins.Text.Acts.SetVisible,
    C3.Plugins.TiledBg.Acts.Destroy,
    C3.Plugins.Text.Acts.SetText,
    C3.Plugins.System.Exps.projectversion,
    C3.Plugins.System.Cnds.Compare,
    C3.Plugins.System.Exps.loadingprogress,
    C3.Plugins.System.Exps.imageloadingprogress,
    C3.Plugins.System.Cnds.TriggerOnce,
    C3.Plugins.System.Acts.SetVar,
    C3.Behaviors.Fade.Acts.RestartFade,
    C3.Plugins.System.Acts.Wait,
    C3.Plugins.Touch.Cnds.OnTouchStart,
    C3.Plugins.Text.Cnds.IsVisible,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.System.Acts.GoToLayout,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.LocalStorage.Acts.GetItem,
    C3.Plugins.LocalStorage.Cnds.OnItemGet,
    C3.Plugins.LocalStorage.Exps.ItemValue,
    C3.Plugins.LocalStorage.Cnds.OnItemMissing,
    C3.Plugins.Touch.Cnds.OnHoldGestureObject,
    C3.Plugins.System.Acts.RestartLayout,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.System.Acts.SetGroupActive,
    C3.Plugins.Sprite.Acts.SetDefaultColor,
    C3.Plugins.Sprite.Acts.MoveToLayer,
    C3.Plugins.Sprite.Acts.SetY,
    C3.Plugins.Sprite.Exps.Y,
    C3.Behaviors.Tween.Acts.TweenOneProperty,
    C3.Plugins.System.Exps.random,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.Spritefont2.Acts.Destroy,
    C3.Plugins.System.Cnds.ForEach,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.System.Exps.choose,
    C3.Plugins.System.Exps.dt,
    C3.Plugins.System.Acts.SetTimescale,
    C3.Plugins.Audio.Acts.SetVolume,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Plugins.Audio.Acts.FadeVolume,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.System.Exps.layoutwidth,
    C3.Plugins.System.Exps.layoutheight,
    C3.Plugins.TiledBg.Acts.MoveToBottom,
    C3.Plugins.TiledBg.Acts.SetSize,
    C3.Plugins.Sprite.Acts.MoveToTop,
    C3.Plugins.Text.Acts.MoveToTop,
    C3.Plugins.Text.Acts.SetFontColor,
    C3.Plugins.Text.Acts.TypewriterText,
    C3.Plugins.Text.Exps.Text,
    C3.Plugins.Touch.Cnds.OnTouchObject,
    C3.Plugins.Sprite.Cnds.IsVisible,
    C3.Plugins.Browser.Cnds.IsFullscreen,
    C3.Plugins.Browser.Acts.CancelFullScreen,
    C3.Plugins.System.Cnds.Else,
    C3.Plugins.Browser.Acts.RequestFullScreen,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.Sprite.Cnds.CompareFrame,
    C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
    C3.Plugins.System.Cnds.CompareBoolVar,
    C3.Plugins.Sprite.Exps.Count,
    C3.Plugins.Sprite.Acts.MoveToBottom,
    C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
    C3.Plugins.Sprite.Cnds.CompareInstanceVar,
    C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
    C3.Plugins.Sprite.Exps.X,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.Sprite.Exps.AnimationFrame,
    C3.Behaviors.Pin.Acts.PinByProperties,
    C3.Behaviors.Flash.Acts.Flash,
    C3.Plugins.System.Acts.SetBoolVar,
    C3.Plugins.Sprite.Acts.SetOpacity,
    C3.Plugins.Sprite.Acts.SetSize,
    C3.Plugins.Sprite.Exps.Width,
    C3.Plugins.Sprite.Exps.Height,
    C3.Behaviors.Tween.Acts.TweenTwoProperties,
    C3.Plugins.Sprite.Exps.ImageWidth,
    C3.Plugins.Sprite.Exps.ImageHeight,
    C3.Plugins.Sprite.Acts.SetInstanceVar,
    C3.Plugins.Sprite.Cnds.IsOnScreen,
    C3.Plugins.System.Cnds.For,
    C3.Plugins.System.Cnds.PickByComparison,
    C3.Plugins.Sprite.Exps.IID,
    C3.Plugins.System.Exps.loopindex,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Plugins.System.Cnds.PickOverlappingPoint,
    C3.Plugins.Sprite.Acts.SetPos,
    C3.Plugins.Keyboard.Cnds.OnKey,
    C3.Plugins.Sprite.Cnds.OnFrameChanged,
    C3.Plugins.System.Exps.layoutname,
    C3.Behaviors.Fade.Acts.SetFadeInTime,
    C3.Behaviors.Fade.Acts.SetWaitTime,
    C3.Behaviors.Fade.Acts.SetFadeOutTime,
    C3.Plugins.Sprite.Cnds.CompareOpacity,
    C3.Plugins.Audio.Cnds.IsTagPlaying,
    C3.Plugins.Audio.Acts.SetSilent,
    C3.Plugins.System.Cnds.LayerVisible,
    C3.Plugins.System.Acts.SetLayerVisible,
    C3.Plugins.System.Exps.tokenat,
    C3.Plugins.Text.Cnds.CompareInstanceVar,
    C3.Plugins.Text.Acts.SetInstanceVar,
  ];
};
self.C3_JsPropNameTable = [
  { Fade: 0 },
  { intro_: 0 },
  { Sine: 0 },
  { txt_taptocontinue: 0 },
  { Touch: 0 },
  { debug: 0 },
  { Audio: 0 },
  { LocalStorage: 0 },
  { fade: 0 },
  { Anchor: 0 },
  { txt_reset: 0 },
  { btn_main: 0 },
  { btn_sound: 0 },
  { btn_music: 0 },
  { bgPaused: 0 },
  { b_play: 0 },
  { txt_ver: 0 },
  { warning: 0 },
  { txt_score: 0 },
  { fontSizeDefault: 0 },
  { txt_gameover: 0 },
  { Tween: 0 },
  { btn_restartGame: 0 },
  { btn_restart: 0 },
  { btn_fullscreen: 0 },
  { btn_info: 0 },
  { txt_infoBack: 0 },
  { title: 0 },
  { Browser: 0 },
  { readyToMatch: 0 },
  { first: 0 },
  { up: 0 },
  { pieceDelay: 0 },
  { block: 0 },
  { launcher: 0 },
  { bottom: 0 },
  { frame: 0 },
  { checker: 0 },
  { propagator: 0 },
  { blockSelected: 0 },
  { fixPos: 0 },
  { Pin: 0 },
  { txt_credits: 0 },
  { btn_gotit: 0 },
  { displayTexts: 0 },
  { order: 0 },
  { txt_howTo: 0 },
  { btn_howtoPage: 0 },
  { tuto: 0 },
  { highlight: 0 },
  { Keyboard: 0 },
  { Flash: 0 },
  { effectNewMax: 0 },
  { block10: 0 },
  { Rotate: 0 },
  { effect10rotate: 0 },
  { ChatGPTImage13DeJunDe202508_13_: 0 },
  { TopButtons: 0 },
  { load_ok: 0 },
  { storageName: 0 },
  { score: 0 },
  { hScore: 0 },
  { gameStarted: 0 },
  { matches: 0 },
  { tweenRunning: 0 },
  { tweenTime: 0 },
  { toAddToScore: 0 },
  { maxBlock: 0 },
  { delayTouch: 0 },
  { posX: 0 },
  { posY: 0 },
  { value: 0 },
  { Sound: 0 },
  { Music: 0 },
  { fadeTime: 0 },
  { type: 0 },
  { firstTime: 0 },
];

self.InstanceType = {
  intro_: class extends self.ISpriteInstance {},
  txt_taptocontinue: class extends self.ITextInstance {},
  Touch: class extends self.IInstance {},
  debug: class extends self.ISpriteFontInstance {},
  Audio: class extends self.IInstance {},
  LocalStorage: class extends self.IInstance {},
  fade: class extends self.ITiledBackgroundInstance {},
  txt_reset: class extends self.ITextInstance {},
  btn_main: class extends self.ISpriteInstance {},
  btn_sound: class extends self.ISpriteInstance {},
  btn_music: class extends self.ISpriteInstance {},
  bgPaused: class extends self.ITiledBackgroundInstance {},
  b_play: class extends self.ISpriteInstance {},
  txt_ver: class extends self.ITextInstance {},
  warning: class extends self.ITextInstance {},
  txt_score: class extends self.ITextInstance {},
  txt_gameover: class extends self.ITextInstance {},
  btn_restartGame: class extends self.ISpriteInstance {},
  btn_restart: class extends self.ISpriteInstance {},
  btn_fullscreen: class extends self.ISpriteInstance {},
  btn_info: class extends self.ISpriteInstance {},
  txt_infoBack: class extends self.ITextInstance {},
  title: class extends self.ISpriteInstance {},
  Browser: class extends self.IInstance {},
  block: class extends self.ISpriteInstance {},
  launcher: class extends self.ISpriteInstance {},
  bottom: class extends self.ISpriteInstance {},
  checker: class extends self.ISpriteInstance {},
  propagator: class extends self.ISpriteInstance {},
  blockSelected: class extends self.ISpriteInstance {},
  fixPos: class extends self.ISpriteInstance {},
  txt_credits: class extends self.ITextInstance {},
  btn_gotit: class extends self.ISpriteInstance {},
  txt_howTo: class extends self.ITextInstance {},
  btn_howtoPage: class extends self.ISpriteInstance {},
  tuto: class extends self.ISpriteInstance {},
  highlight: class extends self.ISpriteInstance {},
  Keyboard: class extends self.IInstance {},
  effectNewMax: class extends self.ISpriteInstance {},
  block10: class extends self.ISpriteInstance {},
  effect10rotate: class extends self.ISpriteInstance {},
  ChatGPTImage13DeJunDe202508_13_: class extends self.ISpriteInstance {},
  TopButtons: class extends self.ISpriteInstance {},
};
