var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_WIN = "YOU WIN";
var TEXT_SCORE = "SCORE";
var TEXT_MOVES = "MOVES";
var TEXT_ARE_YOU_SURE = "ARE YOU SURE?";

var TEXT_HELP1 = "CARDS CAN BE BUILT IN RANK DESCENDING ORDER";
var TEXT_HELP2 = "YOU CAN PICK AND DRAG ONLY CARDS OF THE SAME SUIT";
var TEXT_HELP3 = "THE PURPOSE IS TO REMOVE ALL CARDS FROM THE GAME BOARD BY SCORING ROYAL FLUSHES (OF THE SAME SUIT), FROM KING TO ACE";

var TEXT_HINT1 = "DECK CARDS CAN'T BE DISTRIBUTED IF THERE ARE EMPTY COLUMNS!!";
var TEXT_HINT2 = "NO MORE MOVES AVAILABLE, CLICK RESTART BUTTON!";

var TEXT_GAME_OVER = "GAME OVER";
var TEXT_STALL = "IN ORDER TO DEAL A NEW ROW ALL COLUMNS MUST CONTAIN AT LEAST 1 CARD.\nYOU DON'T HAVE ENOUGH CARDS TO DO IT.";

var TEXT_HELP1_PAGE2 = "SCORE SYSTEM";
var TEXT_HELP2_PAGE2 = "You can earn +%s points by scoring a royal flush";
var TEXT_LOSE1_PAGE2 = "Don't use too many moves. You lose %s point every move";

var TEXT_MODE_1 = "1 SUIT";
var TEXT_MODE_2 = "2 SUITS";
var TEXT_MODE_3 = "4 SUITS";
var TEXT_EASY = "EASY";
var TEXT_NORMAL = "MEDIUM";
var TEXT_HARD = "HARD";
var TEXT_TOP_MODE = "CHOSE GAME MODE";

var TEXT_DEVELOPED = "developed by";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";